gcc program1.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 1
gcc program2.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 2
gcc program3.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 3
gcc program4.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 4
gcc program5.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 5
gcc program6.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 6
gcc program7.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 7
gcc program8.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 8
gcc program9.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 9
gcc program10.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 10
gcc program11.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 11
gcc program12.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 12
gcc program13.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 13
gcc program14.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 14
gcc program15.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 15
gcc program16.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 16
gcc program17.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 17
gcc program18.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 18
gcc program19.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 19
gcc program20.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 20
gcc program21.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 21
gcc program22.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 22
gcc program23.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 23
gcc program24.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 24
gcc program25.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 25
gcc program26.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 26
gcc program27.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 27
gcc program28.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 28
gcc program29.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 29
gcc program30.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 30
gcc program31.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 31
gcc program32.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 32
gcc program33.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 33
gcc program34.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 34
gcc program35.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 35
gcc program36.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 36
gcc program37.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 37
gcc program38.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 38
gcc program39.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 39
gcc program40.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 40
gcc program41.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 41
gcc program42.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 42
gcc program43.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 43
gcc program44.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 44
gcc program45.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 45
gcc program46.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 46
gcc program47.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 47
gcc program48.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 48
gcc program49.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 49
gcc program50.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 50
gcc program51.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 51
gcc program52.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 52
gcc program53.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 53
gcc program54.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 54
gcc program55.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 55
gcc program56.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 56
gcc program57.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 57
gcc program58.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 58
gcc program59.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 59
gcc program60.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 60
gcc program61.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 61
gcc program62.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 62
gcc program63.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 63
gcc program64.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 64
gcc program65.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 65
gcc program66.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 66
gcc program67.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 67
gcc program68.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 68
gcc program69.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 69
gcc program70.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 70
gcc program71.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 71
gcc program72.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 72
gcc program73.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 73
gcc program74.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 74
gcc program75.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 75
gcc program76.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 76
gcc program77.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 77
gcc program78.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 78
gcc program79.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 79
gcc program80.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 80
gcc program81.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 81
gcc program82.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 82
gcc program83.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 83
gcc program84.c -fno-stack-protector -fno-pie -fno-plt -no-pie -m32 -o 84
